name: build ⚙️

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    name: Test JSON artifact generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements 📦
        run: |
          python -m pip install --upgrade pip
      - name: Run ⚙️
        run: |
          python3 -mjson.tool live-deployments.geojson
          python3 -mjson.tool community/psc.geojson

